### ISSUE TITLE
The script not working 

### ISSUE THREAD

**Issue by youresofunny** [royalapplications/toolbox#24]
We created a new folder with proper permissions (user logged in to RoyalTS is owner of the folder) - not pushing or still missing in RoyalTS. Is the script designed for 10.9.x Secrer Server?

**Comment by lemonmojo** [comment]
@youresofunny We will need a little bit more information to begin troubleshooting your issue. Stuff that can help us:
* Which error message do you get?
* Has it ever worked and only started failing after a recent update?
* Screenshots showing how you configured your dynamic folder

Since this is likely to contain sensitive data, it's probably a good idea to [open a support ticket](https://www.royalapps.com/go/support-ticket-new) instead of posting this publicly on Github.
