### ISSUE TITLE
Store Secret's username and password from Secret Server to RoyalTS

### ISSUE THREAD

**Issue by pmkpa** [royalapplications/toolbox#32]
Hi,
I would like to ask if there is a way to modify current script in order to store username and passwords of the secrets in RoyalTS. I tried to modify the script but i could only retrieve Secret's confiiguration info and not username and password.

**Comment by StefanKoell** [comment]
I'm not sure I understand. To successfully connect to your secret server, you need to configure the dynamic folder credentials with your username/password you use to authenticate against the Secret Server. Once this is done, you should be able to connect. You can either specify username or password directly on the dynamic folder object or you refer to a credential by name or point to an existing credential stored in one of your documents.

**Comment by pmkpa** [comment]
> I'm not sure I understand. To successfully connect to your secret server, you need to configure the dynamic folder credentials with your username/password you use to authenticate against the Secret Server. Once this is done, you should be able to connect. You can either specify username or password directly on the dynamic folder object or you refer to a credential by name or point to an existing credential stored in one of your documents.

Hello Stefan,
I have successfully retrieved the secrets in RoyalTS from Secret Server with my credentials. Secrets are stored in RoyalTS as credentials. When i edit the properties of the retrieved Secrets Username and password are not displayed as shown in the picture
![image](https://user-images.githubusercontent.com/74908191/148831830-0353bd36-b50c-404a-8767-4eb312dfb3b4.png)

Do you know if it is possible to store and display username and password of Secrets in RoyalTS ? 
Thanks in advance

**Comment by StefanKoell** [comment]
Thanks for the clarification. The reason you don't see the username/password, is because the script creates a dynamic credential. In order to actually get the username and password, a dynamic credential script needs to be called right before the connection is established:
https://docs.royalapps.com/r2021/royalts/reference/organization/dynamic-folder.html#-dynamic-credential-script

This is by design because secret server's auditing will track each and every access to your credentials (secrets). Replacing the dynamic credentials with regular credentials including username and password is possible but not advised because it would cause a lot of audits to be written every time you "reload" the dynamic folder in Royal TS.

Does this make sense?
