### ISSUE TITLE
rjson - Redirect Drives

### ISSUE THREAD

**Issue by nicovs** [royalapplications/toolbox#63]
hi Stefan,
Not sure if this is the correct place to create this issue... :)

Could you check out this Royal Rjson issue i'm encountering. When i create an rjson files with some objects like this:
```
		{
    		"Type": "RemoteDesktopConnection",
			"Name": "PowerBox [192.168.1.101]",
			"ComputerName": "192.168.1.101",
			"Username": "nicovs",
			"Password": "olalalapassword",
			"Description": "Prosol PowerBox [192.168.1.101]",
			"Port": "3389",
			"RedirectClipboard": "True",
                         "RedirectDrives": "True",
	                 "NetworkLevelAuthentication": "True"
		},
```
I cannot get the Drive Redirection to work on Mac or Windows
![Properties_2023-03-03_17h56](https://user-images.githubusercontent.com/1900299/222780465-2635cd52-28ac-4433-9ad2-71b41adfe758.jpg)
![powerbox_2023-03-03_20h04](https://user-images.githubusercontent.com/1900299/222805360-094d503a-35a3-4d6b-a80a-d9770ab50152.jpg)

**Comment by StefanKoell** [comment]
Hi!

In order to set arbitrary properties, put them under the *Properties* path. See also: https://docs.royalapps.com/r2021/scripting/rjson/advanced-scenarios.html 

You should also put the other "advanced" properties there. Also check out the json schema to see which properties can be set directly: https://docs.royalapps.com/r2021/scripting/rjson/json-schema.html

Let me know if this helps.
Stefan

**Comment by nicovs** [comment]
Yes! much better... tnx :)

Nico
